<div class="pagination" style="margin-left: 50%; font-size: 2rem;">
    <a href="#">&laquo;</a>
    <a href="#">1</a>
    <a href="#" class="active">2</a>
    <a href="#">3</a>
    <a href="#">4</a>
    <a href="#">5</a>
    <a href="#">6</a>
    <a href="#">&raquo;</a>
</div>
<?php
 /**
  * @var \Inchoo\Sample\Block\ListAction $block
  */
    foreach($block->display()->getItems() as $item){
        echo 'id: ' . $item->getId() . '<br>';
        echo 'title: ' . $item->getNewsTitle() . '<br>';
        echo 'content: ' . $item->getNewsContent() . '<hr>';
    }
    ?>
