<?php
/**
 * @var \Inchoo\Sample03\Block\ListAction $block
 */
?>

<table>
    <tr>
        <th>Created at</th>
        <th>Updated at</th>
        <th>Title</th>
        <th>Content</th>

    </tr>
    <?php     foreach($block->getProductCollection() as $item): ?>
    <tr>
        <td><?php echo $item->getCreatedAt(); ?></td>
        <td><?php echo $item->getUpdatedAt(); ?></td>
        <td><?php echo $item->getTitle(); ?></td>
        <td><?php echo $item->getContent(); ?></td>
    </tr>
    <?php endforeach; ?>
</table>

