<?php
/**
 * @var \Inchoo\Sample03\Block\View $block
 */
?>

<?php
    if(!$block->getNewsWithId()){
        echo "There is no user with that id";
        return;
    }
?>

<table>
    <tr>
        <th>Created at</th>
        <th>Updated at</th>
        <th>Title</th>
        <th>Content</th>

    </tr>
    <?php
        $item = $block->getNewsWithId(); ?>
        <tr>
            <td><?php echo $item->getCreatedAt(); ?>
            <td><?php echo $item->getUpdatedAt(); ?></td>
            <td><?php echo $item->getTitle(); ?></td>
            <td><?php echo $item->getContent(); ?></td>
        </tr>
</table>